### ISSUE TITLE
Poetry not working for me 

### ISSUE THREAD

**Issue by IsaiahT-Tech** [IsaiahT-Tech/cryptography-api#8]
I am not sure if I put the wrong command. But the `poetry shell` is not working.

**Comment by SnkSynthesis** [comment]
@IsaiahT-Tech 

If `poetry shell` is displaying output similar to this:
```bash
$ poetry shell
Virtual environment already activated: /home/USER/.cache/pypoetry/virtualenvs/cryptography-api-eex34mhC-py3.8
```
then you can __EITHER__ put `poetry run` before every command e.g. `poetry run python -m unittest` so that it will run the command in the `virtualenv` that `poetry` has created
__OR__
You can copy the path that the output said or in the example's case: `/home/USER/.cache/pypoetry/virtualenvs/cryptography-api-eex34mhC-py3.8` and run this command (different for windows):

`$ source /home/USER/.cache/pypoetry/virtualenvs/cryptography-api-eex34mhC-py3.8/bin/activate`

this will activate the `virtualenv` that `poetry` has created.

**Comment by IsaiahT-Tech** [comment]
Thank you so much @SnkSynthesis.
